version: 0.2

phases:
    install:
        commands:
        - echo start install
        - apt-get install php7.1-zip
        - apt-get install php7.1-gd 
        
    pre_build:
        commands:
        - composer install --no-dev -o
        - cd ~/webroot/grav
        - bin/grav install
        
    build:
        commands:
        - echo start build on 'date'
        - composer test